# Generated by Django 6.0.5 on 2026-05-29 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('service', models.CharField(choices=[('drone_spraying', 'Drone Spraying'), ('tractor_rental', 'Tractor Rental'), ('rotavator', 'Rotavator'), ('harvester', 'Harvester'), ('seed_drill', 'Seed Drill'), ('water_tanker', 'Water Tanker'), ('cultivator', 'Cultivator'), ('fertilizer_spraying', 'Fertilizer Spraying')], max_length=30)),
                ('crop', models.CharField(max_length=50)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.CharField(max_length=50)),
                ('location_address', models.TextField()),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('field_photo', models.ImageField(blank=True, upload_to='field_photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('operator_assigned', 'Operator Assigned'), ('on_the_way', 'On The Way'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_bookings', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
