# Generated by Django 5.2.7 on 2026-07-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_kycdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('operator', 'Operator'), ('dealer', 'Dealer'), ('manager', 'Area Manager')], default='farmer', max_length=10),
        ),
    ]
