# Generated by Django 5.2.7 on 2026-07-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('operator', 'Operator'), ('dealer', 'Dealer'), ('manager', 'Area Manager'), ('admin', 'Admin')], default='farmer', max_length=10),
        ),
    ]
