# Generated by Django 5.2.7 on 2026-07-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_admin_role_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_license',
            field=models.BooleanField(default=False),
        ),
    ]
