# Generated by Django 6.0.7 on 2026-08-06 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_needs_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='doc_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('driving_license', 'Driving License')], max_length=16),
        ),
        migrations.CreateModel(
            name='TrainingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('drone_pilot', 'Drone Pilot Certification'), ('pesticide', 'Pesticide Application License'), ('tractor', 'Tractor Operator Certification')], max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
