# Generated by Django 6.0.7 on 2026-08-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_kycdocument_doc_type_trainingapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='push_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
