# Generated by Django 6.0.5 on 2026-06-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_district_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
