# Generated by Django 6.0.5 on 2026-06-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometric_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='login_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
