# Generated by Django 6.0.5 on 2026-06-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_biometric_token_user_login_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biometric_token',
        ),
        migrations.AddField(
            model_name='user',
            name='biometric_devices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
