# Generated by Django 6.0.5 on 2026-06-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_biometric_token_user_biometric_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_on_duty',
            field=models.BooleanField(default=False),
        ),
    ]
