# Generated by Django 6.0.5 on 2026-06-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='spray_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
