# Generated by Django 6.0.7 on 2026-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_amount_default_zero'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('drone_spraying', 'Drone Spraying'), ('tractor_rental', 'Tractor Rental'), ('rotavator', 'Rotavator'), ('harvester', 'Harvester'), ('seed_drill', 'Seed Drill'), ('water_tanker', 'Water Tanker'), ('cultivator', 'Cultivator'), ('fertilizer_spraying', 'Fertilizer Spraying')], help_text='Leave blank to apply to all services', max_length=30)),
                ('district', models.CharField(blank=True, help_text='Leave blank to apply to all districts', max_length=100)),
                ('commission_percent', models.DecimalField(decimal_places=2, help_text='e.g. 10 for 10%', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-service', '-district'],
                'unique_together': {('service', 'district')},
            },
        ),
    ]
