# Generated by Django 6.0.7 on 2026-08-06 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_commissionrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(blank=True, help_text='Set when operator/manager books on behalf of farmer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
